# Main configuration file
# This defines the default composition of configs

defaults:
  - _self_
  - dataset: mvfouls
  - model: mvit
  - training: baseline
  - loss: focal
  - sampling: progressive
  - freezing: progressive
  - system: single_gpu
  - experiment: default

# Global settings that can override sub-configs
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra:job.num} 